### ISSUE TITLE
增加主界面日期更新的功能

### ISSUE THREAD

**Issue by homedew8** [Forairaaaaa/ChappieUI#1]
注意到大佬当前的工程中，主界面日期似乎不会更新，于是我在App_Launcher.cpp中简单添加了一下更新日期的功能。
[App_Launcher.zip](https://github.com/Forairaaaaa/ChappieUI/files/11209179/App_Launcher.zip)

**Comment by Forairaaaaa** [comment]
> 注意到大佬当前的工程中，主界面日期似乎不会更新，于是我在App_Launcher.cpp中简单添加了一下更新日期的功能。 [App_Launcher.zip](https://github.com/Forairaaaaa/ChappieUI/files/11209179/App_Launcher.zip)

可以直接 pull request ~
